apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: dotnetserver
  newName: nicksonendlich/gitopsfc
  newTag: c485462407bb45f0ce2897b4f466976797c63f8e
